# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvopenhackteam5-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "5ce50122-72ea-4069-9bbc-ee342209741f"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kvopenhackteam5"        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_USER
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_PASSWORD
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLDBNAME
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_DBNAME
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLSERVER
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_SERVER
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: a41ea392-df41-4501-848b-ee7dda22a543                 # The tenant ID of the key vault