apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryhkl1754.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: SQL_SERVER
          value: sqlserverhkl1754.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: ClusterIP
  ports:
  - port: 80 
    targetPort: 80
    name: http-userprofile-port
  selector:
    app: userprofile
